# Generated by Django 5.0.6 on 2026-10-03 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='joined_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
