# Generated by Django 5.0.14 on 2026-10-03 09:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('datetime', models.DateTimeField(help_text='Event start date and time')),
                ('venue', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum attendee capacity (must be at least 1)', validators=[django.core.validators.MinValueValidator(1)])),
                ('member_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ticket price for active members (>= 0.00)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('nonmember_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ticket price for non-members (>= 0.00)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', help_text='Event status: draft, published, or closed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['datetime'],
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('capacity__gte', 1)), name='event_capacity_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('member_price__gte', Decimal('0.00'))), name='event_member_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('nonmember_price__gte', Decimal('0.00'))), name='event_nonmember_price_gte_0'),
        ),
    ]
