# Generated by Django 5.0.14 on 2026-10-03 09:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(blank=True, default='', max_length=255)),
                ('holder_email', models.EmailField(blank=True, default='', max_length=254)),
                ('type', models.CharField(choices=[('member', 'Member'), ('nonmember', 'Non-Member')], default='nonmember', help_text='Ticket pricing tier: member or nonmember', max_length=20)),
                ('price_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual monetary price paid for the ticket', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID token for QR code and check-in', unique=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('checked_in', 'Checked In'), ('cancelled', 'Cancelled')], default='valid', help_text='Ticket status: valid, checked_in, or cancelled', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='Event for which this ticket was issued', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
                ('holder', models.ForeignKey(blank=True, help_text='User account holding the ticket (optional for guests)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='ticket_event_status_idx'), models.Index(fields=['token'], name='ticket_token_idx')],
            },
        ),
    ]
