# Generated by Django 5.1.15 on 2026-10-03 09:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Product name (e.g., 'Skyline Club Navy Hoodie')", max_length=255)),
                ('type', models.CharField(choices=[('hoodie', 'Hoodie'), ('tee', 'T-Shirt'), ('cap', 'Cap / Hat'), ('sweatshirt', 'Sweatshirt'), ('accessory', 'Accessory'), ('sticker', 'Sticker'), ('other', 'Other')], default='tee', help_text='Product category/type', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Base retail price (must be greater than 0.00)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True, default='', help_text='Detailed product description and fabric details')),
                ('image', models.CharField(blank=True, default='', help_text='Product image URL or static asset path', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is displayed in the active store')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='Variant size (e.g. XS, S, M, L, XL, One Size)', max_length=30)),
                ('stock_qty', models.IntegerField(default=0, help_text='Available inventory stock quantity for this size (must be >= 0)', validators=[django.core.validators.MinValueValidator(0)])),
                ('sku', models.CharField(blank=True, default='', help_text='Optional SKU identifier', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Parent product this variant belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['product', 'size'],
                'unique_together': {('product', 'size')},
            },
        ),
    ]
