# Generated by Django 5.1.15 on 2026-10-03 10:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', Decimal('0.00'))), name='product_price_strictly_positive'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('stock_qty__gte', 0)), name='variant_stock_qty_non_negative'),
        ),
    ]
