# Generated by Django 5.1.15 on 2026-10-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_orderitem_order_order_total_non_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(default='mock', help_text="Payment gateway provider used ('mock', 'stripe', 'cash', etc.)", max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, default='', help_text='External transaction / intent ID from payment provider', max_length=255),
        ),
    ]
