# Generated by Django 5.1.15 on 2026-10-03 13:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Fundraiser or project name (e.g. 'Annual Fall Bake Sale Fundraiser')", max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Project scope, goals, location, and volunteer guidelines')),
                ('goal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fundraising target goal amount ($)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', help_text='Current execution status of the project/fundraiser', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Officer or leader who initiated the project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project / Fundraiser',
                'verbose_name_plural': 'Projects & Fundraisers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Action item (e.g. 'Bake 3 dozen cookies', 'Buy supplies', 'Run checkout table 12-2pm')", max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed checklist, shift schedule, or supply specifications')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('doing', 'In Progress'), ('done', 'Done')], default='todo', help_text='Workflow status: todo, doing, or done', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Task urgency level', max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='Target completion deadline date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, help_text='Assigned volunteer or club member responsible for this action item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Parent fundraiser or project this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.project')),
            ],
            options={
                'verbose_name': 'Volunteer Task',
                'verbose_name_plural': 'Volunteer Tasks',
                'ordering': ['due_date', 'status', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('goal_amount__gte', Decimal('0.00'))), name='project_goal_amount_non_negative'),
        ),
    ]

