# Generated by Django 5.0.6 on 2026-10-03 10:32

import django.core.validators
import django.db.models.deletion
import finance.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Requested reimbursement amount (must be strictly positive)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(help_text='Itemized reason or details for expense')),
                ('receipt', models.FileField(blank=True, help_text='Receipt image or PDF proof', null=True, upload_to='reimbursements/receipts/', validators=[finance.models.validate_receipt_file])),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', help_text='Current approval and disbursement status', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Officer notes or rejection reasons')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, help_text='Officer who reviewed/approved the reimbursement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reimbursements', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(help_text='Member/Volunteer requesting reimbursement', on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, help_text='Central ledger transaction recorded upon approval (prevents double-recording)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement', to='core.transaction')),
            ],
            options={
                'verbose_name': 'Reimbursement',
                'verbose_name_plural': 'Reimbursements',
                'ordering': ['-created_at'],
            },
        ),
    ]
