# Generated by Django 5.0.6 on 2026-10-03 10:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('days_before_expiry', models.IntegerField()),
                ('email_to', models.EmailField(max_length=254)),
                ('message_body', models.TextField()),
                ('status', models.CharField(default='sent', max_length=20)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='members.membership')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
