# Generated by Django 5.1.15 on 2026-10-03 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Headline or title of the announcement', max_length=200)),
                ('body', models.TextField(help_text='Detailed content of the announcement')),
                ('audience', models.CharField(choices=[('all', 'All Club Members'), ('members', 'Active Members Only'), ('volunteers', 'Volunteers')], default='all', help_text='Target audience for dispatch and visibility', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when recorded')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when last updated')),
                ('is_sent', models.BooleanField(default=False, help_text='Indicates whether email dispatch has occurred')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Timestamp when announcement was emailed', null=True)),
                ('author', models.ForeignKey(blank=True, help_text='Author/Officer who created the announcement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
