# Generated by Django 5.0.6 on 2026-10-03 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Subscribed email address', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Active subscription status')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Optional linked User account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailing_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mailing List Subscriber',
                'verbose_name_plural': 'Mailing List Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
