# Generated by Django 5.0.6 on 2026-10-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_mailinglistsubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
    ]
